// COLOR BRANDING

export const COLOR_BRAND_PRIMARY = '#0576FF';

// COLOR SUPORTE

export const COLOR_SUPORTE_SUCCESS = '#20CB59';

export const COLOR_SUPORTE_WARNING = '#F9CD47';

export const COLOR_SUPORTE_DANGER = '#F94770';

// COLOR GREYSCALE (NEUTRAL)

export const COLOR_NEUTRAL_BLACK = '#19191C';

export const COLOR_NEUTRAL_DARKEST = '#4C4F59';

export const COLOR_NEUTRAL_DARK = '#8B909E';

export const COLOR_NEUTRAL_MEDIUM = '#CBCED6';

export const COLOR_NEUTRAL_LIGHT = '#EDEDED';

export const COLOR_NEUTRAL_LIGHTEST = '#F7F9FA';

export const COLOR_NEUTRAL_WHITE = '#F5F6F5';
